### ISSUE TITLE
Training service error: GPU not available. Please check your CUDA configuration

### ISSUE THREAD

**Issue by whtlook** [microsoft/nni#1919]
I use Windows 10 ,anaconda with python 3.6.9.
I have tensorflow-gpu==1.12.0 installed, I use pip install not conda.
I have CUDA9.0 and cudnn 7.6.5 downloaded from official website, and add them to path.

![path](https://user-images.githubusercontent.com/45705345/71713366-5e1f8800-2e44-11ea-8516-2c0ade8d47ec.PNG)

tensorflow can detect my GPU:
![tensorflow can detect GPU](https://user-images.githubusercontent.com/45705345/71713030-da18d080-2e42-11ea-9fce-581a243dcd64.PNG)

but I can't run tfv1 example code on GPU by setting gpuNum: 1 in config_windows.yml.

![error](https://user-images.githubusercontent.com/45705345/71713172-8b1f6b00-2e43-11ea-9046-a0b303d0e7d8.png)

but i can run the trial with gpuNum: 0, but it's slow.

![success](https://user-images.githubusercontent.com/45705345/71713489-eb62dc80-2e44-11ea-99d8-84733b999b78.PNG)

here is my nnimanager.log
[2020-1-3 15:58:57] INFO [ 'Datastore initialization done' ]
[2020-1-3 15:58:57] INFO [ 'RestServer start' ]
[2020-1-3 15:58:57] INFO [ 'Construct local machine training service.' ]
[2020-1-3 15:58:57] INFO [ 'RestServer base port is 8080' ]
[2020-1-3 15:58:57] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2020-1-3 15:59:00] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python mnist.py","codeDir":"C:\\\\Users\\\\Administrator\\\\nni\\\\examples\\\\trials\\\\mnist-tfv1\\\\.","gpuNum":1}' ]
[2020-1-3 15:59:00] INFO [ 'required GPU number is 1' ]
[2020-1-3 15:59:02] INFO [ 'Starting experiment: mUGhTwYi' ]
[2020-1-3 15:59:02] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2020-1-3 15:59:02] INFO [ 'Add event listeners' ]
[2020-1-3 15:59:02] INFO [ 'Run local machine training service.' ]
[2020-1-3 15:59:02] ERROR [ 'Error: GPU not available. Please check your CUDA configuration\n    at GPUScheduler.run (c:\\users\\administrator\\anaconda3\\nni\\training_service\\local\\gpuScheduler.js:25:23)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' ]
[2020-1-3 15:59:02] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
[2020-1-3 15:59:02] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2020-1-3 15:59:02] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"dropout_rate": 0.6108380734786315, "conv_size": 7, "hidden_size": 512, "batch_size": 4, "learning_rate": 0.1}, "parameter_index": 0}' ]

it seems that the gpuScheduler can not find my GPU. 
I have searched Issues for answer but i can't find one that can solve my problem.
HELP

**Comment by SparkSnail** [comment]
Hi @whtlook, NNI use `nvidia-smi` command to collect gpu information, could you please check if `nvidia-smi` command could work in your machine?

**Comment by whtlook** [comment]
Add C:\Program Files\NVIDIA Corporation\NVSMI to my path and it's done.

**Comment by whtlook** [comment]
Actually I found that it doesn't need tensorflow-gpu to run. And it works with python 3.7.5 and pytorch 1.3.

**Comment by ridgepolesun** [comment]
i have the same problem,and 'nvidia-smi' command  work well ,my device system is ubuntu

**Comment by Emma0120** [comment]
I have the same issue and 'nvidia-smi' command work well in my environment
